global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'microservice'
    static_configs:
      - targets: ['microservice:4000']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"
